USE koha_mapping_db;

CREATE TABLE `aqbasket` (
  `basketno` int(11) NOT NULL AUTO_INCREMENT,
  `basketname` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `note` mediumtext COLLATE utf8_unicode_ci DEFAULT NULL,
  `booksellernote` mediumtext COLLATE utf8_unicode_ci DEFAULT NULL,
  `contractnumber` int(11) DEFAULT NULL,
  `creationdate` date DEFAULT NULL,
  `closedate` date DEFAULT NULL,
  `booksellerid` int(11) NOT NULL DEFAULT 1,
  `authorisedby` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
  `booksellerinvoicenumber` mediumtext COLLATE utf8_unicode_ci DEFAULT NULL,
  `basketgroupid` int(11) DEFAULT NULL,
  `deliveryplace` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
  `billingplace` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
  `branch` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
  `is_standing` tinyint(1) NOT NULL DEFAULT 0,
  `create_items` enum('ordering','receiving','cataloguing') COLLATE utf8_unicode_ci DEFAULT NULL,
  `ALEPH_Z68_REC_KEY` varchar(25) NOT NULL,
  PRIMARY KEY (`basketno`),
  KEY `booksellerid` (`booksellerid`),
  KEY `basketgroupid` (`basketgroupid`),
  KEY `contractnumber` (`contractnumber`),
  KEY `authorisedby` (`authorisedby`),
  KEY `aqbasket_ibfk_4` (`branch`),
  CONSTRAINT `aqbasket_ibfk_1` FOREIGN KEY (`booksellerid`) REFERENCES `aqbooksellers` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `aqbasket_ibfk_2` FOREIGN KEY (`contractnumber`) REFERENCES `aqcontract` (`contractnumber`),
  CONSTRAINT `aqbasket_ibfk_3` FOREIGN KEY (`basketgroupid`) REFERENCES `aqbasketgroups` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `aqbasket_ibfk_4` FOREIGN KEY (`branch`) REFERENCES `branches` (`branchcode`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci