USE koha_mapping_db;

CREATE TABLE `aqorders` (
  `ordernumber` int(11) NOT NULL AUTO_INCREMENT,
  `biblionumber` int(11) DEFAULT NULL,
  `entrydate` date DEFAULT NULL,
  `quantity` smallint(6) DEFAULT NULL,
  `currency` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
  `listprice` decimal(28,6) DEFAULT NULL,
  `datereceived` date DEFAULT NULL,
  `invoiceid` int(11) DEFAULT NULL,
  `freight` decimal(28,6) DEFAULT NULL,
  `unitprice` decimal(28,6) DEFAULT NULL,
  `unitprice_tax_excluded` decimal(28,6) DEFAULT NULL,
  `unitprice_tax_included` decimal(28,6) DEFAULT NULL,
  `quantityreceived` smallint(6) NOT NULL DEFAULT 0,
  `datecancellationprinted` date DEFAULT NULL,
  `cancellationreason` text COLLATE utf8_unicode_ci DEFAULT NULL,
  `order_internalnote` mediumtext COLLATE utf8_unicode_ci DEFAULT NULL,
  `order_vendornote` mediumtext COLLATE utf8_unicode_ci DEFAULT NULL,
  `purchaseordernumber` mediumtext COLLATE utf8_unicode_ci DEFAULT NULL,
  `basketno` int(11) DEFAULT NULL,
  `timestamp` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `rrp` decimal(13,2) DEFAULT NULL,
  `rrp_tax_excluded` decimal(28,6) DEFAULT NULL,
  `rrp_tax_included` decimal(28,6) DEFAULT NULL,
  `ecost` decimal(13,2) DEFAULT NULL,
  `ecost_tax_excluded` decimal(28,6) DEFAULT NULL,
  `ecost_tax_included` decimal(28,6) DEFAULT NULL,
  `tax_rate_bak` decimal(6,4) DEFAULT NULL,
  `tax_rate_on_ordering` decimal(6,4) DEFAULT NULL,
  `tax_rate_on_receiving` decimal(6,4) DEFAULT NULL,
  `tax_value_bak` decimal(28,6) DEFAULT NULL,
  `tax_value_on_ordering` decimal(28,6) DEFAULT NULL,
  `tax_value_on_receiving` decimal(28,6) DEFAULT NULL,
  `discount` float(6,4) DEFAULT NULL,
  `budget_id` int(11) NOT NULL,
  `budgetdate` date DEFAULT NULL,
  `sort1` varchar(80) COLLATE utf8_unicode_ci DEFAULT NULL,
  `sort2` varchar(80) COLLATE utf8_unicode_ci DEFAULT NULL,
  `sort1_authcat` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
  `sort2_authcat` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
  `uncertainprice` tinyint(1) DEFAULT NULL,
  `claims_count` int(11) DEFAULT 0,
  `claimed_date` date DEFAULT NULL,
  `subscriptionid` int(11) DEFAULT NULL,
  `parent_ordernumber` int(11) DEFAULT NULL,
  `orderstatus` varchar(16) COLLATE utf8_unicode_ci DEFAULT 'new',
  `line_item_id` varchar(35) COLLATE utf8_unicode_ci DEFAULT NULL,
  `suppliers_reference_number` varchar(35) COLLATE utf8_unicode_ci DEFAULT NULL,
  `suppliers_reference_qualifier` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,
  `suppliers_report` text COLLATE utf8_unicode_ci DEFAULT NULL,
  `ALEPH_Z68_REC_KEY` varchar(25) NOT NULL,
  PRIMARY KEY (`ordernumber`),
  KEY `basketno` (`basketno`),
  KEY `biblionumber` (`biblionumber`),
  KEY `budget_id` (`budget_id`),
  KEY `parent_ordernumber` (`parent_ordernumber`),
  KEY `orderstatus` (`orderstatus`),
  KEY `aqorders_ibfk_3` (`invoiceid`),
  KEY `aqorders_subscriptionid` (`subscriptionid`),
  KEY `aqorders_currency` (`currency`),
  CONSTRAINT `aqorders_budget_id_fk` FOREIGN KEY (`budget_id`) REFERENCES `aqbudgets` (`budget_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `aqorders_currency` FOREIGN KEY (`currency`) REFERENCES `currency` (`currency`) ON DELETE SET NULL ON UPDATE SET NULL,
  CONSTRAINT `aqorders_ibfk_1` FOREIGN KEY (`basketno`) REFERENCES `aqbasket` (`basketno`) ON DELETE CASCADE ON UPDATE CASCADE #,
 # CONSTRAINT `aqorders_ibfk_2` FOREIGN KEY (`biblionumber`) REFERENCES `biblio` (`biblionumber`) ON DELETE SET NULL ON UPDATE CASCADE,
 # CONSTRAINT `aqorders_ibfk_3` FOREIGN KEY (`invoiceid`) REFERENCES `aqinvoices` (`invoiceid`) ON DELETE SET NULL ON UPDATE CASCADE,
 # CONSTRAINT `aqorders_subscriptionid` FOREIGN KEY (`subscriptionid`) REFERENCES `subscription` (`subscriptionid`) ON DELETE CASCADE ON UPDATE CASCADE #TODO: Add once subscriptions are done
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci