USE koha_mapping_db;

CREATE TABLE `branches` (
  `branchcode` varchar(10) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `branchname` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `branchaddress1` mediumtext COLLATE utf8_unicode_ci DEFAULT NULL,
  `branchaddress2` mediumtext COLLATE utf8_unicode_ci DEFAULT NULL,
  `branchaddress3` mediumtext COLLATE utf8_unicode_ci DEFAULT NULL,
  `branchzip` varchar(25) COLLATE utf8_unicode_ci DEFAULT NULL,
  `branchcity` mediumtext COLLATE utf8_unicode_ci DEFAULT NULL,
  `branchstate` mediumtext COLLATE utf8_unicode_ci DEFAULT NULL,
  `branchcountry` text COLLATE utf8_unicode_ci DEFAULT NULL,
  `branchphone` mediumtext COLLATE utf8_unicode_ci DEFAULT NULL,
  `branchfax` mediumtext COLLATE utf8_unicode_ci DEFAULT NULL,
  `branchemail` mediumtext COLLATE utf8_unicode_ci DEFAULT NULL,
  `branchreplyto` mediumtext COLLATE utf8_unicode_ci DEFAULT NULL,
  `branchreturnpath` mediumtext COLLATE utf8_unicode_ci DEFAULT NULL,
  `branchurl` mediumtext COLLATE utf8_unicode_ci DEFAULT NULL,
  `issuing` tinyint(4) DEFAULT NULL,
  `branchip` varchar(15) COLLATE utf8_unicode_ci DEFAULT NULL,
  `branchprinter` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `branchnotes` mediumtext COLLATE utf8_unicode_ci DEFAULT NULL,
  `opac_info` text COLLATE utf8_unicode_ci DEFAULT NULL,
  `geolocation` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `marcorgcode` varchar(16) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`branchcode`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `branches`
(`branchcode`,`branchname`,`branchaddress1`,`branchaddress2`,`branchaddress3`,`branchzip`,`branchcity`,`branchstate`,`branchcountry`,`branchphone`,`branchfax`,`branchemail`,`branchreplyto`,`branchreturnpath`,`branchurl`,`issuing`,`branchip`,`branchprinter`,`branchnotes`,`opac_info`)
VALUES
('BASSM','Archäologische Staatssammlung, Museum für Vor- und Frühgeschichte, München',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('BBSA','Bibliothek der British School at Athens','Odos Souedias 52','','','10676','Athen','','Griechenland','','','','','','',NULL,'',NULL,'',''),
('BIAUL','Institut Archeologii der Uniwersytet Marii Curie-Sklodowskiej, Lublin ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('BICUAZ','Bibliothek des International Centre for Underwater Archaeology Zadar',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('BLDMV','Landesamt für Denkmalpflege Mecklenburg-Vorpommern ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('BWINCK','Bibliothek der Winckelmann-Gesellschaft, Stendal','','','','','','','','','','','','','',NULL,'',NULL,'',''),
('DAIA','DAI Athen','Odos Fidiou 1','','','10678','Athen','','Griechenland','+30 210 3307 400','','bibliothek.athen@dainst.de','','','https://www.dainst.org/standort/athen/bibliothek',NULL,'',NULL,'','<table class=\"text9\" style=\"color: #000000; font-family: \'Times New Roman\';\">\r\n<tbody>\r\n<tr>\r\n<td style=\"vertical-align: top;\">Adresse:</td>\r\n<td>Deutsches Arch&auml;ologisches Institut&nbsp;<br />Abteilung Athen&nbsp;<br />Bibliothek&nbsp;<br />Fidiou 1&nbsp;<br />106 78 Athen<br />Greece</td>\r\n</tr>\r\n<tr>\r\n<td style=\"vertical-align: top;\">&Ouml;ffnungszeiten:</td>\r\n<td>Mo. - Fr. 9:00 - 20:00 Uhr<br />Sa. 9:00 - 13:30 Uhr</td>\r\n</tr>\r\n<tr>\r\n<td style=\"vertical-align: top;\">Telefon:</td>\r\n<td>+30 210 3307 400</td>\r\n</tr>\r\n<tr>\r\n<td style=\"vertical-align: top;\">Fax:</td>\r\n<td>+30 210 3814762</td>\r\n</tr>\r\n<tr>\r\n<td style=\"vertical-align: top;\">E-Mail:</td>\r\n<td><a href=\"mailto:bibliothek.athen@dainst.de\">bibliothek.athen(at)dainst.de</a></td>\r\n</tr>\r\n</tbody>\r\n</table>'),
('DAIB','DAI KAAK, Bonn','Dürenstr. 35-37','','','53173','Bonn','Nordrhein-Westfalen','Deutschland','','','bibliothek.kaak@dainst.de','','','',NULL,'',NULL,'','<table class=\"text9\">\r\n<tbody>\r\n<tr>\r\n<td style=\"vertical-align: top;\">Adresse:</td>\r\n<td>Kommission f&uuml;r Arch&auml;ologie <br /> Au&szlig;ereurop&auml;ischer Kulturen (KAAK) <br /> des Deutschen Arch&auml;oglogischen Instituts<br /> Bibliothek <br /> D&uuml;renstra&szlig;e 35-37 <br /> 53173 Bonn<br /> Germany</td>\r\n</tr>\r\n<tr>\r\n<td align=\"left\" valign=\"top\">&Ouml;ffnungszeiten:</td>\r\n<td>Mo. - Do. 08:30 - 16:00 Uhr</td>\r\n</tr>\r\n<tr>\r\n<td style=\"vertical-align: top;\">Telefon:</td>\r\n<td>+49 228 997712 17<br /> +49 228 997712 18</td>\r\n</tr>\r\n<tr>\r\n<td style=\"vertical-align: top;\">Fax:</td>\r\n<td>+49 228 997712 49</td>\r\n</tr>\r\n</tbody>\r\n</table>'),
('DAID','DAI, Außenstelle Damaskus','8, Malki Street ','POB 11870','','','Damaskus ','','Syrien','+963 11 374 9812 0','','sekretariat@damaskus.dainst.org','','','https://www.dainst.org/standort/damaskus/bibliothek',NULL,'',NULL,'','<table class=\"text9\">\r\n<tbody>\r\n<tr>\r\n<td style=\"vertical-align: top;\">Adresse:</td>\r\n<td>Deutsches Arch&auml;ologisches Institut<br /> Au&szlig;enstelle Damaskus der Orient-Abteilung<br /> 8, Malki Street <br /> POB 11870 <br /> Damaskus-Malki<br /> Syria</td>\r\n</tr>\r\n<tr>\r\n<td style=\"vertical-align: top;\">Telefon:</td>\r\n<td>+963 11 374 9812 0</td>\r\n</tr>\r\n<tr>\r\n<td style=\"vertical-align: top;\">Fax:</td>\r\n<td>+963 11 374 9812 9</td>\r\n</tr>\r\n<tr>\r\n<td style=\"vertical-align: top;\">E-Mail:</td>\r\n<td><a href=\"mailto:sekretariat@damaskus.dainst.org\">sekretariat(at)damaskus.dainst.org</a></td>\r\n</tr>\r\n</tbody>\r\n</table>'),
('DAIE','DAI Eurasien-Abteilung','Im Dol 2-6','','','14195','Berlin','Berlin','Deutschland','+49 30 187711 335, -336','','bibliothek.eurasien@dainst.de','','','https://www.dainst.org/standort/eurasien/bibliothek',NULL,'',NULL,'','<table class=\"text9\">\r\n<tbody>\r\n<tr>\r\n<td style=\"vertical-align: top;\">&nbsp;Adresse:</td>\r\n<td>Deutsches Arch&auml;ologisches Institut<br /> Eurasien-Abteilung<br /> Bibliothek <br /> Im Dol 2-6, Haus IV<br /> 14195 Berlin<br /> Germany</td>\r\n</tr>\r\n<tr>\r\n<td style=\"vertical-align: top;\">&Ouml;ffnungszeiten:</td>\r\n<td>Mo. - Do. 9:00 - 12:30 Uhr; 13:00 - 15:00 Uhr<br /> Fr. 09:00 -12:30 Uhr; 13:00 - 14:30 Uhr</td>\r\n</tr>\r\n<tr>\r\n<td>Telefon:</td>\r\n<td>+49 30 187711 366<br /> +49 30 187711 335</td>\r\n</tr>\r\n<tr>\r\n<td>Fax:</td>\r\n<td>+49 30 187711 313</td>\r\n</tr>\r\n<tr>\r\n<td style=\"vertical-align: top;\">E-Mail:</td>\r\n<td><a href=\"mailto:bibliothek.eurasien@dainst.de\">bibliothek.eurasien(at)dainst.de</a></td>\r\n</tr>\r\n</tbody>\r\n</table>'),
('DAIF','DAI RGK, Frankfurt am Main','Palmengartenstraße 10-12 ','','','60325','Frankfurt a.M.','Hessen','Deutschland','+49 69 975818 21, -42','','bibliothek.rgk@dainst.de','','','https://www.dainst.org/standort/rgk-frankfurt/bibliothek',NULL,'',NULL,'','<table class=\"text9\">\r\n<tbody>\r\n<tr>\r\n<td style=\"vertical-align: top;\">Adresse:</td>\r\n<td>Deutsches Arch&auml;ologisches Institut <br /> Bibliothek der R&ouml;misch-Germanischen Kommission (RGK) Frankfurt a.M.<br /> Palmengartenstra&szlig;e 10-12<br /> 60325 Frankfurt a.M.<br /> Germany</td>\r\n</tr>\r\n<tr>\r\n<td style=\"vertical-align: top;\">&Ouml;ffnungszeiten:</td>\r\n<td>Mo. - Do. 08:00 - 17:00 Uhr <br /> Fr. 08:00 - 12:30 Uhr</td>\r\n</tr>\r\n<tr>\r\n<td style=\"vertical-align: top;\">Telefon:</td>\r\n<td>+49 69 975818 21 <br /> +49 69 975818 42</td>\r\n</tr>\r\n<tr>\r\n<td style=\"vertical-align: top;\">Fax:</td>\r\n<td>+49 69 975818 38</td>\r\n</tr>\r\n<tr>\r\n<td style=\"vertical-align: top;\">E-Mail:</td>\r\n<td><a href=\"mailto:bibliothek.rgk@dainst.de\">bibliothek.rgk(at)dainst.de </a></td>\r\n</tr>\r\n</tbody>\r\n</table>'),
('DAIG','DAI Gesamt E','','','','','','','','','','','','','',NULL,'',NULL,'',''),
('DAII','DAI Istanbul','Inönü Caddesi 10','','','34437','Istanbul','','Türkei','+90 212 393 76 00','','bibliothek.istanbul@dainst.de','','','https://www.dainst.org/standort/istanbul/bibliothek',NULL,'',NULL,'','<table class=\"text9\">\r\n<tbody>\r\n<tr>\r\n<td style=\"vertical-align: top;\">Adresse:</td>\r\n<td>Deutsches Arch&auml;ologisches Institut<br /> Abteilung Istanbul<br /> Bibliothek<br /> İn&ouml;n&uuml; Caddesi 10<br /> 34437 Istanbul<br /> Turkey</td>\r\n</tr>\r\n<tr>\r\n<td>&Ouml;ffnungszeiten:</td>\r\n<td>Mo. - Fr. 9:00 - 13:00 Uhr</td>\r\n</tr>\r\n<tr>\r\n<td style=\"vertical-align: top;\">Telefon:</td>\r\n<td>+90 212 393 76 00</td>\r\n</tr>\r\n<tr>\r\n<td style=\"vertical-align: top;\">Fax:</td>\r\n<td>+90 212 393 76 40 (Verwaltung)</td>\r\n</tr>\r\n<tr>\r\n<td style=\"vertical-align: top;\">E-Mail:</td>\r\n<td><a href=\"mailto:bibliothek.istanbul@dainst.de\">bibliothek.istanbul(at)dainst.de</a></td>\r\n</tr>\r\n</tbody>\r\n</table>'),
('DAIK','DAI Kairo','31, Abu el Feda','','','11211 ','Kairo - Zamalek ','','Ägypten ','+20 2 2735 1460','','bibliothek.kairo@dainst.de','','','https://www.dainst.org/standort/kairo/bibliothek',NULL,'',NULL,'','<table class=\"text9\">\r\n<tbody>\r\n<tr>\r\n<td style=\"vertical-align: top;\">Adresse:</td>\r\n<td>Deutsches Arch&auml;ologisches Institut <br /> Abteilung Kairo <br /> Bibliothek <br /> 31, Abu el Feda <br /> 11211 Kairo-Zamalek<br /> Egypt</td>\r\n</tr>\r\n<tr>\r\n<td style=\"vertical-align: top;\">&Ouml;ffnungszeiten:</td>\r\n<td>Mo. - Do. 09:00 - 13:00 Uhr<br /> So. 09:00 - 16:00 Uhr</td>\r\n</tr>\r\n<tr>\r\n<td style=\"vertical-align: top;\">Telefon:</td>\r\n<td>+20 2 2735 1460<br /> +20 2 2735 2321</td>\r\n</tr>\r\n<tr>\r\n<td style=\"vertical-align: top;\">Fax:</td>\r\n<td>+20 2 2737 0770</td>\r\n</tr>\r\n<tr>\r\n<td style=\"vertical-align: top;\">E-Mail:</td>\r\n<td><a href=\"mailto:bibliothek.kairo@dainst.de\">bibliothek.kairo(at)dainst.de</a></td>\r\n</tr>\r\n</tbody>\r\n</table>'),
('DAIM','DAI Madrid','Calle Serrano, 159','','','28002','Madrid','','Spanien','+34 91 561 09 04','','bibliothek.madrid@dainst.de','','','https://www.dainst.org/standort/madrid/bibliothek',NULL,'',NULL,'','<table class=\"text9\">\r\n<tbody>\r\n<tr>\r\n<td style=\"vertical-align: top;\">Adresse:</td>\r\n<td>Deutsches Arch&auml;ologisches Institut<br /> Abteilung Madrid<br /> Bibliothek<br /> Serrano, 159<br /> 28002 Madrid<br /> Spain</td>\r\n</tr>\r\n<tr>\r\n<td style=\"vertical-align: top;\">&Ouml;ffnungszeiten:</td>\r\n<td>Mo. - Do. 09:00 - 18.00 Uhr<br /> Fr. 09:00 - 15.00 Uhr<br /> vom 15.06.2012 bis 15.09.2012:<br /> Mo. - Fr. 09.00- 15.00 Uhr</td>\r\n</tr>\r\n<tr>\r\n<td style=\"vertical-align: top;\">Telefon:</td>\r\n<td>+34 91 561 09 04 (Auskunft)</td>\r\n</tr>\r\n<tr>\r\n<td style=\"vertical-align: top;\">Fax:</td>\r\n<td>+34 91 564 00 54</td>\r\n</tr>\r\n<tr>\r\n<td style=\"vertical-align: top;\">E-Mail:</td>\r\n<td><a href=\"mailto:bibliothek.madrid@dainst.de\">bibliothek.madrid(at)dainst.de</a></td>\r\n</tr>\r\n</tbody>\r\n</table>'),
('DAIO','DAI Orient-Abteilung','Podbielskiallee 69-71','','','14195 ','Berlin ','Berlin','Deutschland','+49 3018 7711 173','','bibliothek.orient@dainst.de','','','https://www.dainst.org/standort/orient/bibliothek',NULL,'',NULL,'','<table class=\"text9\">\r\n<tbody>\r\n<tr>\r\n<td style=\"vertical-align: top;\">Adresse:</td>\r\n<td>Deutsches Arch&auml;ologisches Institut <br /> Orient-Abteilung<br /> Bibliothek <br /> Podbielskiallee 69-71 <br /> 14195 Berlin<br /> Germany</td>\r\n</tr>\r\n<tr>\r\n<td style=\"vertical-align: top;\">&Ouml;ffnungszeiten:</td>\r\n<td>Mo. - Fr. 09.00 - 14.00 Uhr</td>\r\n</tr>\r\n<tr>\r\n<td style=\"vertical-align: top;\">Telefon:</td>\r\n<td>+49 3018 7711 173</td>\r\n</tr>\r\n<tr>\r\n<td style=\"vertical-align: top;\">Fax:</td>\r\n<td>+49 1888 7711 189</td>\r\n</tr>\r\n<tr>\r\n<td style=\"vertical-align: top;\">E-Mail:</td>\r\n<td><a href=\"mailto:bibliothek.orient@dainst.de\">bibliothek.orient(at)dainst.de</a></td>\r\n</tr>\r\n</tbody>\r\n</table>'),
('DAIP','DAI, Außenstelle Peking','Unit 1310, Landmark Tower 2, No. 8 North Dongsanhuan Road ','Chaoyang District ','','100004','Peking','','V.R. China ','+86 (0)10 65907071','','daipeking@dainst.de','','','https://dainst.org/standort/peking',NULL,'',NULL,'',''),
('DAIR','DAI Rom','Via Valadier, 37','','','00193 ','Rom ','','Italien','+39 06 488814 1','','bibliothek.rom@dainst.de','','','https://www.dainst.org/standort/rom/bibliothek',NULL,'',NULL,'','<table class=\"text9\">\r\n<tbody>\r\n<tr>\r\n<td style=\"vertical-align: top;\">Adresse:</td>\r\n<td>Deutsches Arch&auml;ologisches Institut <br /> Abteilung Rom <br /> Bibliothek <br /> Via Valadier, 37<br /> I - 00193 Rom<br /> Italien</td>\r\n</tr>\r\n<tr>\r\n<td style=\"vertical-align: top;\">&Ouml;ffnungszeiten:</td>\r\n<td>Die Bibliothek zur Arch&auml;ologie der Mittelmeerl&auml;nder steht Wissenschaftlern mit abgeschlossener Hochschulausbildung zu folgenden Uhrzeiten zur Verf&uuml;gung:<br /> Mo. - Fr. 09:30 - 18:30 Uhr</td>\r\n</tr>\r\n<tr>\r\n<td style=\"vertical-align: top;\">Telefon:</td>\r\n<td>+39 06 488814 1</td>\r\n</tr>\r\n<tr>\r\n<td style=\"vertical-align: top;\">Fax:</td>\r\n<td>+39 06 4884973</td>\r\n</tr>\r\n</tbody>\r\n</table>'),
('DAIS','DAI, Außenstelle Sanaa','Embassy of the Federal Republic of Germany,  Bibliothek ','POB 2562 ','','','Sanaa','','Jemen','+967 (0)1 287 175/177-0','','dai.sanaa@y.net.ye','','','https://www.dainst.org/standort/sanaa/bibliothek',NULL,'',NULL,'','<table class=\"text9\">\r\n<tbody>\r\n<tr>\r\n<td align=\"left\" valign=\"top\">Adresse:</td>\r\n<td>Orient-Abteilung, Au&szlig;enstelle Sanaa<br /> German Archaeological Institute <br /> Embassy of the Federal Republic of Germany<br /> Bibliothek<br /> POB 2562 <br /> Sanaa<br /> Republic of Yemen</td>\r\n</tr>\r\n<tr>\r\n<td style=\"vertical-align: top;\">Telefon:</td>\r\n<td>+967 1 287 175<br /> +967 1 287 177 0</td>\r\n</tr>\r\n<tr>\r\n<td style=\"vertical-align: top;\">Fax:</td>\r\n<td>+967 1 485 213</td>\r\n</tr>\r\n<tr>\r\n<td style=\"vertical-align: top;\">E-Mail:</td>\r\n<td><a href=\"mailto:dai.sanaa@y.net.ye\">dai.sanaa(at)y.net.ye</a></td>\r\n</tr>\r\n</tbody>\r\n</table>'),
('DAIT','DAI, Außenstelle Teheran','Khiaban-e Shahid Akbari 9, P.O. Box 3894 ','','','','Tehran -Elahiyeh ','','','+98 (0)21-2221 63 39','','teheran@dainst.de','','','https://www.dainst.org/organisation/71351',NULL,'',NULL,'',''),
('DAIZ','DAI Zentrale','Podbielskiallee 69-71','','','14195','Berlin','Berlin','Deutschland','+49 30 187711 146','','bibliothek.zentrale@dainst.de','','','https://www.dainst.org/standort/zentrale/bibliothek',NULL,'',NULL,'','<table class=\"text9\">\r\n<tbody>\r\n<tr>\r\n<td style=\"vertical-align: top;\">Adresse:</td>\r\n<td>Deutsches Arch&auml;ologisches Institut <br /> Bibliothek der Zentrale<br /> Podbielskiallee 69-71 <br /> 14195 Berlin <br /> Germany</td>\r\n</tr>\r\n<tr>\r\n<td align=\"left\" valign=\"top\">&Ouml;ffnungszeiten:</td>\r\n<td>Mo. - Do. 09:00 - 16:15 Uhr <br /> Fr. 09:00 - 14:30 Uhr <br /> <span style=\"text-decoration: underline;\">Hinweis:</span> Alle Leser werden gebeten, sich vor der ersten Nutzung der Bibliothek der Zentrale beim dortigen Personal zu melden, da es derzeit nur eine beschr&auml;nkte Anzahl von Lesepl&auml;tzen gibt.</td>\r\n</tr>\r\n<tr>\r\n<td align=\"left\" valign=\"top\">Telefon:</td>\r\n<td>+49 30 187711 146 (Auskunft)</td>\r\n</tr>\r\n<tr>\r\n<td style=\"vertical-align: top;\">Fax:</td>\r\n<td>+49 30 187711 168</td>\r\n</tr>\r\n<tr>\r\n<td style=\"vertical-align: top;\">E-Mail:</td>\r\n<td><a href=\"mailto:bibliothek.zentrale@dainst.de\">bibliothek.zentrale(at)dainst.de</a></td>\r\n</tr>\r\n</tbody>\r\n</table>'),
('DEIA','DEI Amman','Forschungsstelle Amman, Deutsches Evangelisches Institut für Altertumswissenschaft des Heiligen Landes (DEI), zugleich Forschungsstelle des Deutschen Archäologischen Instituts','P.O. Box 183 ','','11118 ','Amman','','Jordanien','+962-6-5342924','','gpia@go.com.jo','','','http://www.deiahl.de/bibliothek-422.html',NULL,'',NULL,'','<table class=\"text9\">\r\n<tbody>\r\n<tr>\r\n<td style=\"vertical-align: top;\">Adresse:</td>\r\n<td>Forschungsstelle Amman, <br /> Deutsches Evangelisches Institut <br /> f&uuml;r Altertumswissenschaft des Heiligen Landes (DEI),<br /> zugleich Forschungsstelle des Deutschen Arch&auml;ologischen Instituts<br /> P.O. Box 183<br /> 11118 Amman<br /> Jordan</td>\r\n</tr>\r\n<tr>\r\n<td align=\"left\" valign=\"top\">&Ouml;ffnungszeiten:</td>\r\n<td>So. - Do. 8:00 - 14:00 Uhr</td>\r\n</tr>\r\n<tr>\r\n<td style=\"vertical-align: top;\">Telefon:</td>\r\n<td>+962 6 5346924</td>\r\n</tr>\r\n<tr>\r\n<td style=\"vertical-align: top;\">Fax:</td>\r\n<td>+962 6 5336924</td>\r\n</tr>\r\n<tr>\r\n<td style=\"vertical-align: top;\">E-Mail:</td>\r\n<td><a href=\"mailto:gpia@go.com.jo\">gpia(at)go.com.jo</a></td>\r\n</tr>\r\n</tbody>\r\n</table>'),
('DEIJ','DEI Jerusalem','','','','','','','','','','dei_ger@netvision.net.il','','','http://www.deiahl.de/bibliothek-102.html',NULL,'',NULL,'','');
