USE koha_mapping_db;

CREATE TABLE `items` (
  `itemnumber` int(11) NOT NULL AUTO_INCREMENT,
  `biblionumber` int(11) NOT NULL DEFAULT '0',
  `biblioitemnumber` int(11) NOT NULL DEFAULT '0',
  `barcode` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dateaccessioned` date DEFAULT NULL,
  `booksellerid` longtext COLLATE utf8mb4_unicode_ci,
  `homebranch` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `price` decimal(8,2) DEFAULT NULL,
  `replacementprice` decimal(8,2) DEFAULT NULL,
  `replacementpricedate` date DEFAULT NULL,
  `datelastborrowed` date DEFAULT NULL,
  `datelastseen` date DEFAULT NULL,
  `stack` tinyint(1) DEFAULT NULL,
  `notforloan` tinyint(1) NOT NULL DEFAULT '0',
  `damaged` tinyint(1) NOT NULL DEFAULT '0',
  `damaged_on` datetime DEFAULT NULL,
  `itemlost` tinyint(1) NOT NULL DEFAULT '0',
  `itemlost_on` datetime DEFAULT NULL,
  `withdrawn` tinyint(1) NOT NULL DEFAULT '0',
  `withdrawn_on` datetime DEFAULT NULL,
  `itemcallnumber` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `coded_location_qualifier` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `issues` smallint(6) DEFAULT NULL,
  `renewals` smallint(6) DEFAULT NULL,
  `reserves` smallint(6) DEFAULT NULL,
  `restricted` tinyint(1) DEFAULT NULL,
  `itemnotes` longtext COLLATE utf8mb4_unicode_ci,
  `itemnotes_nonpublic` longtext COLLATE utf8mb4_unicode_ci,
  `holdingbranch` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `paidfor` longtext COLLATE utf8mb4_unicode_ci,
  `timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `location` varchar(80) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `permanent_location` varchar(80) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `onloan` date DEFAULT NULL,
  `cn_source` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cn_sort` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ccode` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `materials` mediumtext COLLATE utf8mb4_unicode_ci,
  `uri` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `itype` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `more_subfields_xml` longtext COLLATE utf8mb4_unicode_ci,
  `enumchron` mediumtext COLLATE utf8mb4_unicode_ci,
  `copynumber` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `stocknumber` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `new_status` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`itemnumber`),
  UNIQUE KEY `itembarcodeidx` (`barcode`),
  KEY `itemstocknumberidx` (`stocknumber`),
  KEY `itembinoidx` (`biblioitemnumber`),
  KEY `itembibnoidx` (`biblionumber`),
  KEY `homebranch` (`homebranch`),
  KEY `holdingbranch` (`holdingbranch`),
  KEY `itemcallnumber` (`itemcallnumber`(191)),
  KEY `items_location` (`location`),
  KEY `items_ccode` (`ccode`),
  KEY `itype_idx` (`itype`),
  KEY `timestamp` (`timestamp`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;