version: '3.5'

services:
  koha-mapping-db:
    container_name: koha_mapping_db
    build:
      context: lib
    ports:
      - '3307:3306'
    volumes:
      - 'koha_mapping_data:/var/lib/mysql'
    networks:
      - network_1

volumes:
  koha_mapping_data: {}

networks:
  network_1:
    name: zenon_migration_network