USE koha_mapping_db;

CREATE TABLE `aqbooksellers` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `address1` mediumtext COLLATE utf8_unicode_ci,
  `address2` mediumtext COLLATE utf8_unicode_ci,
  `address3` mediumtext COLLATE utf8_unicode_ci,
  `address4` mediumtext COLLATE utf8_unicode_ci,
  `phone` varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL,
  `accountnumber` mediumtext COLLATE utf8_unicode_ci,
  `othersupplier` mediumtext COLLATE utf8_unicode_ci,
  `currency` varchar(10) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `booksellerfax` mediumtext COLLATE utf8_unicode_ci,
  `notes` mediumtext COLLATE utf8_unicode_ci,
  `bookselleremail` mediumtext COLLATE utf8_unicode_ci,
  `booksellerurl` mediumtext COLLATE utf8_unicode_ci,
  `postal` mediumtext COLLATE utf8_unicode_ci,
  `url` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `active` tinyint(4) DEFAULT NULL,
  `listprice` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
  `invoiceprice` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
  `gstreg` tinyint(4) DEFAULT NULL,
  `listincgst` tinyint(4) DEFAULT NULL,
  `invoiceincgst` tinyint(4) DEFAULT NULL,
  `tax_rate` decimal(6,4) DEFAULT NULL,
  `discount` float(6,4) DEFAULT NULL,
  `fax` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `deliverytime` int(11) DEFAULT NULL,
  `ALEPH_VENDOR_KEY` varchar(25) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `listprice` (`listprice`),
  KEY `invoiceprice` (`invoiceprice`),
  KEY `name` (`name`(255)),
  CONSTRAINT `aqbooksellers_ibfk_1` FOREIGN KEY (`listprice`) REFERENCES `currency` (`currency`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `aqbooksellers_ibfk_2` FOREIGN KEY (`invoiceprice`) REFERENCES `currency` (`currency`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci